/*
┌────────────────────────────┐
│　Description: 生成脚本用途说明
│　Remark: 
└────────────────────────────┘
*/

using Cysharp.Text;
using Lin.Editor.Settings;
using Lin.Runtime.Helper;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.Concurrent;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;
using UnityEditor.Callbacks;

namespace Lin.Editor.ScriptTool
{
    public static class ScriptDescriptionMarkDownGenerator
    {
        [MenuItem("Lin/脚本/生成Description汇总")]
        public static void GenerateMarkDown()
        {
            var settings = EditorSettings_SO.GetInstance();
            var filters = settings.descriptionFilters is null ? new List<string>() : new List<string>(settings.descriptionFilters);

            string projectRoot = new DirectoryInfo(Application.dataPath).Parent.FullName;
            string outputPath = Path.Combine(projectRoot, settings.docsOutputFolderName, "ScriptDescriptions.md");

            var scriptGuids = AssetDatabase.FindAssets("t:MonoScript");
            var scriptPaths = new List<string>(scriptGuids.Length);
            for (int i = 0; i < scriptGuids.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(scriptGuids[i]);
                if (string.IsNullOrEmpty(path))
                    continue;

                if (!path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
                    continue;

                scriptPaths.Add(path);
            }

            var attributeResults = CollectAttributeDescriptions(projectRoot);
            var scriptAssemblyMap = CollectScriptAssemblyMap(scriptPaths);

            Task.Run(() =>
            {
                try
                {
                    var results = CollectDescriptionsInBackground(projectRoot, filters, scriptPaths, attributeResults, scriptAssemblyMap);
                    string content = BuildMarkdown(results, projectRoot);
                    WriteMarkdown(content, outputPath);

                    EditorApplication.delayCall += () =>
                        Log.Debug(nameof(ScriptDescriptionMarkDownGenerator), ZString.Format("已生成: {0}/ScriptDescriptions.md (共 {1} 条)", EditorSettings_SO.GetInstance().docsOutputFolderName, results.Count));
                }
                catch (Exception e)
                {
                    EditorApplication.delayCall += () =>
                        Log.Error(nameof(ScriptDescriptionMarkDownGenerator), $"生成失败 {e.Message}");
                }
            });
        }

        [DidReloadScripts]
        private static void AutoGenerateOnScriptReload()
        {
            try
            {
                var settings = EditorSettings_SO.GetInstance();
                if (!settings.autoGenerateDescriptionMarkdown)
                    return;

                EditorApplication.delayCall += GenerateMarkDown;
            }
            catch
            {
            }
        }

        private static Dictionary<string, string> CollectScriptAssemblyMap(List<string> scriptPaths)
        {
            var map = new Dictionary<string, string>(scriptPaths.Count, StringComparer.Ordinal);
            for (int i = 0; i < scriptPaths.Count; i++)
            {
                string path = scriptPaths[i];
                string assemblyName = CompilationPipeline.GetAssemblyNameFromScriptPath(path);
                assemblyName = NormalizeAssemblyName(assemblyName);
                if (string.IsNullOrEmpty(assemblyName))
                    continue;

                map[path] = assemblyName;
            }

            return map;
        }

        private static List<Result> CollectAttributeDescriptions(string projectRoot)
        {
            var results = new List<Result>(256);
            var types = TypeCache.GetTypesWithAttribute<DescriptionAttribute>();
            foreach (var type in types)
            {
                if (type is null)
                    continue;

                if (!IsClassOrStruct(type))
                    continue;

                var attributes = type.GetCustomAttributes(typeof(DescriptionAttribute), false);
                if (attributes is null || attributes.Length == 0)
                    continue;

                var attribute = attributes[0] as DescriptionAttribute;
                if (attribute is null)
                    continue;

                string description = attribute.Description;
                if (string.IsNullOrWhiteSpace(description))
                    continue;

                string scriptPath = TryResolveScriptAssetPath(projectRoot, type);
                string fullPath = TryResolveFullPath(projectRoot, scriptPath);

                results.Add(new Result
                {
                    attributeDescription = description,
                    assemblyName = NormalizeAssemblyName(type.Assembly.GetName().Name),
                    typeFullName = type.FullName,
                    scriptPath = scriptPath,
                    fullPath = fullPath
                });
            }

            return results;
        }

        private static List<Result> CollectDescriptionsInBackground(string projectRoot, List<string> filters, List<string> scriptPaths, List<Result> attributeResults, Dictionary<string, string> scriptAssemblyMap)
        {
            var resultMap = new Dictionary<string, Result>(512, StringComparer.Ordinal);
            for (int i = 0; i < attributeResults.Count; i++)
            {
                var r = attributeResults[i];
                string key = !string.IsNullOrEmpty(r.scriptPath) ? r.scriptPath : r.typeFullName;
                if (string.IsNullOrEmpty(key))
                    continue;

                resultMap[key] = r;
            }

            if (filters != null && filters.Count > 0 && scriptPaths != null && scriptPaths.Count > 0)
            {
                var indexedMap = new ConcurrentDictionary<string, string>(StringComparer.Ordinal);
                Parallel.For(0, scriptPaths.Count, new ParallelOptions { MaxDegreeOfParallelism = Math.Max(1, Environment.ProcessorCount - 1) }, i =>
                {
                    string path = scriptPaths[i];
                    string fileContent;
                    try
                    {
                        fileContent = File.ReadAllText(Path.Combine(projectRoot, path.Replace('/', Path.DirectorySeparatorChar)));
                    }
                    catch
                    {
                        return;
                    }

                    string indexedDescription = FindIndexedDescriptions(fileContent, filters);
                    if (string.IsNullOrWhiteSpace(indexedDescription))
                        return;

                    indexedMap[path] = indexedDescription;
                });

                foreach (var pair in indexedMap)
                {
                    if (!resultMap.TryGetValue(pair.Key, out var result))
                        result = new Result();

                    result.indexedDescription = pair.Value;
                    result.scriptPath = pair.Key;
                    result.fullPath = TryResolveFullPath(projectRoot, pair.Key);
                    if (string.IsNullOrEmpty(result.assemblyName) && scriptAssemblyMap != null && scriptAssemblyMap.TryGetValue(pair.Key, out var assemblyName))
                        result.assemblyName = assemblyName;

                    if (string.IsNullOrEmpty(result.typeFullName))
                        result.typeFullName = Path.GetFileNameWithoutExtension(pair.Key);

                    resultMap[pair.Key] = result;
                }
            }

            var results = new List<Result>(resultMap.Count);
            foreach (var pair in resultMap)
                results.Add(pair.Value);

            results.Sort((a, b) =>
            {
                int c = string.CompareOrdinal(a.assemblyName, b.assemblyName);
                if (c != 0)
                    return c;

                c = string.CompareOrdinal(a.typeFullName, b.typeFullName);
                if (c != 0)
                    return c;

                return string.CompareOrdinal(a.scriptPath, b.scriptPath);
            });

            return results;
        }

        private static string FindIndexedDescriptions(string fileContent, List<string> filters)
        {
            if (string.IsNullOrEmpty(fileContent) || filters is null || filters.Count == 0)
                return null;

            using var sb = ZString.CreateStringBuilder();
            for (int i = 0; i < filters.Count; i++)
            {
                string filter = filters[i];
                if (string.IsNullOrEmpty(filter))
                    continue;

                if (!fileContent.Contains(filter))
                    continue;

                var match = Regex.Match(fileContent, @$"{filter}([^\n]+)");
                if (!match.Success)
                    continue;

                string value = match.Groups[1].Value.Trim();
                if (string.IsNullOrWhiteSpace(value))
                    continue;

                if (sb.Length > 0)
                    sb.Append(" ");

                sb.Append(value);
            }

            if (sb.Length == 0)
                return null;

            return sb.ToString();
        }

        private static bool IsClassOrStruct(Type type)
        {
            if (type.IsClass)
                return true;

            if (type.IsValueType && !type.IsEnum && !type.IsPrimitive)
                return true;

            return false;
        }

        private static string TryResolveScriptAssetPath(string projectRoot, Type type)
        {
            var guids = AssetDatabase.FindAssets(ZString.Format("t:MonoScript {0}", type.Name));
            if (guids is null || guids.Length == 0)
                return string.Empty;

            string bestPath = string.Empty;
            string bestFullPath = string.Empty;
            for (int i = 0; i < guids.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(guids[i]);
                if (string.IsNullOrEmpty(path))
                    continue;

                if (!string.Equals(Path.GetFileNameWithoutExtension(path), type.Name, StringComparison.Ordinal))
                    continue;

                var monoScript = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                if (monoScript != null && type.IsClass && monoScript.GetClass() == type)
                    return path;

                string full = TryResolveFullPath(projectRoot, path);
                if (string.IsNullOrEmpty(bestPath))
                {
                    bestPath = path;
                    bestFullPath = full;
                    continue;
                }

                if (!string.IsNullOrEmpty(full) && string.IsNullOrEmpty(bestFullPath))
                {
                    bestPath = path;
                    bestFullPath = full;
                    continue;
                }

                if (!string.IsNullOrEmpty(full) && full.Contains("Assets", StringComparison.OrdinalIgnoreCase) && !bestFullPath.Contains("Assets", StringComparison.OrdinalIgnoreCase))
                {
                    bestPath = path;
                    bestFullPath = full;
                }
            }

            return bestPath;
        }

        private static string TryResolveFullPath(string projectRoot, string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath))
                return string.Empty;

            if (assetPath.StartsWith("Assets/", StringComparison.Ordinal) || assetPath.StartsWith("Assets\\", StringComparison.Ordinal))
                return Path.Combine(projectRoot, assetPath.Replace('/', Path.DirectorySeparatorChar));

            if (assetPath.StartsWith("Packages/", StringComparison.Ordinal) || assetPath.StartsWith("Packages\\", StringComparison.Ordinal))
            {
                string packagesRoot = Path.Combine(projectRoot, "Packages");
                string candidate = Path.Combine(packagesRoot, assetPath.Replace('/', Path.DirectorySeparatorChar).Substring("Packages/".Length));
                if (File.Exists(candidate))
                    return candidate;
            }

            return string.Empty;
        }

        private static string BuildMarkdown(List<Result> results, string projectRoot)
        {
            using var sb = ZString.CreateStringBuilder();
            sb.AppendLine("# Script Descriptions");
            sb.AppendLine();
            sb.AppendLine(ZString.Format("- 生成时间: {0:yyyy-MM-dd HH:mm:ss}", DateTime.Now));
            sb.AppendLine(ZString.Format("- 条目数: {0}", results.Count));
            sb.AppendLine();

            string lastAssembly = null;
            for (int i = 0; i < results.Count; i++)
            {
                var r = results[i];
                string assemblyName = NormalizeAssemblyName(r.assemblyName);
                assemblyName = string.IsNullOrEmpty(assemblyName) ? "未命名程序集" : assemblyName;
                if (!string.Equals(lastAssembly, assemblyName, StringComparison.Ordinal))
                {
                    if (lastAssembly != null)
                        sb.AppendLine();

                    sb.AppendLine(ZString.Format("## {0}", EscapeMarkdownHeading(assemblyName)));
                    sb.AppendLine();
                    sb.AppendLine("| 描述 | 程序集路径 | 文件路径 |");
                    sb.AppendLine("| --- | --- | --- |");
                    lastAssembly = assemblyName;
                }

                string description = MergeDescription(r.indexedDescription, r.attributeDescription);
                string asmPath = string.IsNullOrEmpty(r.assemblyName) ? r.typeFullName : ZString.Format("{0}::{1}", r.assemblyName, r.typeFullName);
                string filePath = !string.IsNullOrEmpty(r.scriptPath) ? r.scriptPath : ToProjectRelativePath(projectRoot, r.fullPath);
                sb.Append('|');
                sb.Append(EscapeMarkdownCell(description));
                sb.Append('|');
                sb.Append(EscapeMarkdownCell(asmPath));
                sb.Append('|');
                sb.Append(EscapeMarkdownCell(filePath));
                sb.AppendLine("|");
            }

            return sb.ToString();
        }

        private static string NormalizeAssemblyName(string assemblyName)
        {
            if (string.IsNullOrWhiteSpace(assemblyName))
                return string.Empty;

            assemblyName = assemblyName.Trim();
            string fileName = Path.GetFileName(assemblyName);
            if (!string.IsNullOrEmpty(fileName))
                assemblyName = fileName;

            if (assemblyName.EndsWith(".dll", StringComparison.OrdinalIgnoreCase))
                return Path.GetFileNameWithoutExtension(assemblyName);

            return assemblyName;
        }

        private static string EscapeMarkdownHeading(string value)
        {
            if (string.IsNullOrEmpty(value))
                return string.Empty;

            value = value.Replace("\r\n", " ").Replace('\n', ' ').Replace('\r', ' ');
            return value;
        }

        private static string MergeDescription(string indexedDescription, string attributeDescription)
        {
            bool hasIndexed = !string.IsNullOrWhiteSpace(indexedDescription);
            bool hasAttribute = !string.IsNullOrWhiteSpace(attributeDescription);
            if (!hasIndexed && !hasAttribute)
                return string.Empty;

            if (hasIndexed && !hasAttribute)
                return indexedDescription;

            if (!hasIndexed && hasAttribute)
                return attributeDescription;

            if (string.Equals(indexedDescription, attributeDescription, StringComparison.Ordinal))
                return indexedDescription;

            return ZString.Format("{0}<br/>{1}", indexedDescription, attributeDescription);
        }

        private static string ToProjectRelativePath(string projectRoot, string fullPath)
        {
            if (string.IsNullOrEmpty(fullPath))
                return string.Empty;

            if (string.IsNullOrEmpty(projectRoot))
                return fullPath.Replace('\\', '/');

            try
            {
                var rootUri = new Uri(projectRoot.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) + Path.DirectorySeparatorChar);
                var fileUri = new Uri(fullPath);
                string relative = rootUri.MakeRelativeUri(fileUri).ToString();
                return relative.Replace('\\', '/');
            }
            catch
            {
                return fullPath.Replace('\\', '/');
            }
        }

        private static string EscapeMarkdownCell(string value)
        {
            if (string.IsNullOrEmpty(value))
                return string.Empty;

            value = value.Replace("\r\n", "\n");
            value = value.Replace("\n", "<br/>");
            value = value.Replace("|", "\\|");
            return value;
        }

        private static void WriteMarkdown(string markdown, string outputPath)
        {
            string rulesDir = Path.GetDirectoryName(outputPath);
            IOHelper.InsureExist(rulesDir, false);
            File.WriteAllText(outputPath, markdown ?? string.Empty, new UTF8Encoding(false));
        }

        private struct Result
        {
            public string attributeDescription;
            public string indexedDescription;
            public string assemblyName;
            public string typeFullName;
            public string scriptPath;
            public string fullPath;
        }
    }
}
