using Lin.Runtime.Attribute;
using Lin.Runtime.DesignPattern.Singleton;
using Lin.Runtime.Helper;
using System.Collections.Generic;
using UnityEngine;

namespace Lin.Editor.Settings
{
    [AssetPath("Assets/Settings/LinEditorSettings.asset", AssetPathAttribute.ELoaderType.AssetDatabase)]
    public class EditorSettings_SO : ScriptableObjectSingleton<EditorSettings_SO>
    {
        private const string DOCS_OUTPUT_FOLDER_NAME = "Markdown";
        private const string CSHARP_OUTPUT = "Assets/Scripts/Generated";
        public string cSharpOutput;

        //----------------- Docs -----------------
        public string docsOutputFolderName;

        //----------------- EditorSocket -----------------
        public bool editorSocketAutoStart = true;
        public string editorSocketListenAddress = "127.0.0.1";
        public int editorSocketPort = 0;

        //----------------- 资源注释 -----------------
        public List<string> descriptionFilters;
        public int assetSummaryTitleSize = 14;
        public EClickType assetSummaryEditWay = EClickType.单击;

        public int sceneObjectDescriptionTitleSize = 14;
        public EClickType sceneObjectDescriptionEditWay = EClickType.单击;

        public Color scriptDscColor;
        public bool scriptDscBold;
        public bool scriptDscItalic;
        public bool autoGenerateDescriptionMarkdown;

        //----------------- SceneView -----------------
        public bool drawRendererInfos_SV;  // 绘制Renderer的定点数/面数
        public Color infosColor_SV;     // 绘制颜色

        //----------------- RemoteAsset -----------------
        public string downloadFolder;

        //----------------- TODO 过滤 -----------------
        public List<string> todoIgnoreFolders = new List<string>();
        public List<string> todoIgnoreAssemblies = new List<string>();

        public EditorSettings_SO()
        {
            cSharpOutput = CSHARP_OUTPUT;
            docsOutputFolderName = DOCS_OUTPUT_FOLDER_NAME;
            descriptionFilters = new List<string>() { "Description: ", "Description：", "功能说明: " };
            IOHelper.InsureExist("Assets/Settings", false);
        }
    }
}
