/*
┌────────────────────────────┐
│　Description: WebGL单例预加载代码生成器
│　Remark: 自动扫描AssetPathAttribute+Singleton类，生成预加载类
└────────────────────────────┘
*/
using Cysharp.Text;
using Lin.Editor.Settings;
using Lin.Runtime.Attribute;
using Lin.Runtime.DesignPattern.Singleton;
using Lin.Runtime.Helper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEditor;
using UnityEditor.Callbacks;
using ZLinq;

namespace Lin.Editor.Singleton
{
    [InitializeOnLoad]
    public static class SingletonPreloadGenerator
    {
        private const string OUTPUT_FILE = "SingletonPreload.cs";

        [DidReloadScripts]
        private static void OnScriptsReloaded()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
                return;

            Generate();
        }

        [MenuItem("Lin/Generate SingletonPreload")]
        private static void GenerateMenu() => Generate();

        private static void Generate()
        {
            var settings = EditorSettings_SO.GetInstance();
            if (settings == null || string.IsNullOrEmpty(settings.cSharpOutput))
                return;

            var singletonTypes = CollectSingletonTypes();

            using var sb = ZString.CreateStringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by SingletonPreloadGenerator. Do not modify manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine("namespace Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class SingletonPreload");
            sb.AppendLine("    {");
            sb.AppendLine("        public static async UniTask PreloadAsync()");
            sb.AppendLine("        {");

            if (singletonTypes.Count > 0)
            {
                foreach (var type in singletonTypes)
                    sb.AppendLine($"            {type.FullName}.GetInstance();");
                sb.AppendLine("            await UniTask.CompletedTask;");
            }
            else
            {
                sb.AppendLine("            await UniTask.CompletedTask;");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var outputPath = Path.Combine(settings.cSharpOutput, OUTPUT_FILE);
            IOHelper.InsureExist(Path.GetDirectoryName(outputPath), false);

            var newContent = sb.ToString();
            if (File.Exists(outputPath) && File.ReadAllText(outputPath) == newContent)
                return;

            File.WriteAllText(outputPath, newContent);
            Log.Debug(nameof(SingletonPreloadGenerator), $"已生成 {outputPath}");
        }

        private static List<Type> CollectSingletonTypes()
        {
            var result = new List<(Type type, int priority)>();

            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try { types = assembly.GetTypes(); }
                catch { continue; }

                if (IsEditorAssembly(assembly)) continue;

                foreach (var type in types)
                {
                    var attr = type.GetCustomAttribute<AssetPathAttribute>();
                    if (attr == null) continue;
                    if (!IsSingletonType(type)) continue;

                    result.Add((type, attr.Priority));
                }
            }

            return result
                .AsValueEnumerable()
                .OrderBy(t => t.priority)
                .Select(t => t.type)
                .ToList();
        }

        private static bool IsEditorAssembly(Assembly assembly)
        {
            var name = assembly.GetName().Name;
            if (name.EndsWith(".Editor")) return true;
            if (name.Contains(".Editor.")) return true;

            try
            {
                var location = assembly.Location.Replace('\\', '/');
                if (location.Contains("/Editor/"))
                    return true;
            }
            catch { }

            return false;
        }

        private static bool IsSingletonType(Type type)
        {
            var current = type.BaseType;
            while (current != null)
            {
                if (current.IsGenericType)
                {
                    var genericDef = current.GetGenericTypeDefinition();
                    if (genericDef == typeof(MonoSingleton<>) ||
                        genericDef == typeof(ScriptableObjectSingleton<>))
                        return true;
                }
                current = current.BaseType;
            }
            return false;
        }
    }
}
